name: deploy

on:
  push:
    branches: [main, "*.x"]
  pull_request:
    branches: [main, "*.x"]

env:
  DENO_VERSION: v1.x

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "atlas"
          entrypoint: "website/main.ts"
